version: 1.0.{build}
environment:
  ZLIB_VERSION: 1.2.11
install:
- ps: >-
    appveyor DownloadFile "https://github.com/madler/zlib/archive/v$env:ZLIB_VERSION.zip" -FileName zlib.zip

    7z x zlib.zip -oC:\

    Rename-Item -path "c:\zlib-$env:ZLIB_VERSION" -newName "c:\zlib"
before_build:
- cmd: >-
    cd vstudio

    RMDIR /S /Q zlib

    robocopy C:\zlib zlib /S /NP || EXIT /B 0

    .\vsbuild.cmd build+test "Visual Studio 12 Win64" v120
build:
  verbosity: minimal