name: build
on: [push]

jobs:
  all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
#        os: [macos-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install libzstd-dev
      - name: prepare build directory
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
      - name: configure
        working-directory: ${{runner.workspace}}/build
        run: |
          echo running .....cmake $GITHUB_WORKSPACE .....
          cmake $GITHUB_WORKSPACE
      - name: build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build .
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest -v
