name: continuous-integration
on: [push]

jobs:
  all:
#    runs-on: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt-get update -m && sudo apt-get install libzstd-dev
      - name: build
        uses: lukka/run-cmake@v3
