name: continuous-integration
on: [push]

jobs:
  all:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
              sudo apt-get install libzstd-dev
          fi
      - name: prepare build directory
        run: |
          cmake -E make_directory ${{runner.workspace}}/build
      - name: configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE
      - name: build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build .
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: |
          (cd regress; ./liboverride-test -v; find . -print) || true
          ctest -v
